export const LOTTERY_CANDIDATE_ABI = [
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'totalDeposited',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'currentRound',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'entryFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'roundPrizePool',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'round', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'roundEntered',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'round', type: 'uint256' },
      { name: 'account', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'roundWinner',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'round', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'roundDrawn',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'round', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getRoundParticipants',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'round', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    name: 'getRoundParticipantCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'round', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getDepositors',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    name: 'getDepositorCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'candidate',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'depositTON',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'tonAmount', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'depositWTON',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'wtonAmount', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'enterLottery',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'drawWinner',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ name: 'winner', type: 'address' }],
  },
  {
    name: 'updateSeigniorage',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'requestWithdrawal',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'processWithdrawal',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'n', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'setEntryFee',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_entryFee', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'Deposited',
    type: 'event',
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'LotteryEntered',
    type: 'event',
    inputs: [
      { name: 'round', type: 'uint256', indexed: true },
      { name: 'account', type: 'address', indexed: true },
      { name: 'entryFee', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'LotteryWinnerDrawn',
    type: 'event',
    inputs: [
      { name: 'round', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: true },
      { name: 'prizeAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'SeigniorageReceived',
    type: 'event',
    inputs: [{ name: 'amount', type: 'uint256', indexed: false }],
  },
  {
    name: 'SeigniorageDistributed',
    type: 'event',
    inputs: [
      { name: 'totalAmount', type: 'uint256', indexed: false },
      { name: 'depositorCount', type: 'uint256', indexed: false },
    ],
  },
] as const

export const ERC20_ABI = [
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'symbol',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
] as const
