// DelegateStakingV3Upgradeable ABI (v1.3.0)
export const DELEGATE_STAKING_ABI = [
  // Errors
  { inputs: [], name: 'EmergencyNotActive', type: 'error' },
  { inputs: [], name: 'EmergencyCooldownNotElapsed', type: 'error' },
  { inputs: [], name: 'InsufficientBalance', type: 'error' },
  { inputs: [], name: 'InvalidAddress', type: 'error' },
  { inputs: [], name: 'InvalidCommission', type: 'error' },
  { inputs: [], name: 'Layer2AlreadyRegistered', type: 'error' },
  { inputs: [], name: 'Layer2NotEligible', type: 'error' },
  { inputs: [], name: 'NoPendingRewards', type: 'error' },
  { inputs: [], name: 'NoUnstakeRequest', type: 'error' },
  { inputs: [], name: 'SequencerAlreadyRegistered', type: 'error' },
  { inputs: [], name: 'SequencerNotRegistered', type: 'error' },
  { inputs: [], name: 'StakeCooldownNotElapsed', type: 'error' },
  { inputs: [], name: 'Unauthorized', type: 'error' },
  { inputs: [], name: 'UnstakingPeriodNotElapsed', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  { inputs: [], name: 'ZeroAmount', type: 'error' },

  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'enabled', type: 'bool' },
    ],
    name: 'AutoTriggerSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'CommissionClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'oldCommission', type: 'uint256' },
      { indexed: false, name: 'newCommission', type: 'uint256' },
    ],
    name: 'CommissionUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'layer2', type: 'address' },
      { indexed: false, name: 'activatedAt', type: 'uint256' },
    ],
    name: 'EmergencyActivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'layer2', type: 'address' },
    ],
    name: 'EmergencyDeactivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'EmergencyWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: true, name: 'fromSequencer', type: 'address' },
      { indexed: true, name: 'toSequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'Redelegated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'RewardsClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'commission', type: 'uint256' },
      { indexed: false, name: 'distributed', type: 'uint256' },
    ],
    name: 'SeigniorageReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: 'sequencer', type: 'address' }],
    name: 'SequencerDeregistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: true, name: 'layer2', type: 'address' },
      { indexed: true, name: 'operatorManager', type: 'address' },
      { indexed: false, name: 'commission', type: 'uint256' },
    ],
    name: 'SequencerRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'Staked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: true, name: 'sequencer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'unlockTime', type: 'uint256' },
    ],
    name: 'UnstakeRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'staker', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'Withdrawn',
    type: 'event',
  },

  // View Functions
  {
    inputs: [],
    name: 'MAX_COMMISSION',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'STAKE_COOLDOWN',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'layer2', type: 'address' }],
    name: 'checkLayer2Eligibility',
    outputs: [
      { name: 'eligible', type: 'bool' },
      { name: 'requiredStake', type: 'uint256' },
      { name: 'currentStake', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'layer2', type: 'address' }],
    name: 'emergencyInfo',
    outputs: [
      { name: 'isActive', type: 'bool' },
      { name: 'activatedAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'estimateSeigniorage',
    outputs: [
      { name: 'sequencerReward', type: 'uint256' },
      { name: 'validatorReward', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSequencerCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'getSequencerInfo',
    outputs: [
      {
        components: [
          { name: 'isRegistered', type: 'bool' },
          { name: 'layer2', type: 'address' },
          { name: 'operatorManager', type: 'address' },
          { name: 'commission', type: 'uint256' },
          { name: 'totalStaked', type: 'uint256' },
          { name: 'accRewardPerShare', type: 'uint256' },
          { name: 'totalCommission', type: 'uint256' },
          { name: 'autoTrigger', type: 'bool' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSequencerList',
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'staker', type: 'address' },
      { name: 'sequencer', type: 'address' },
    ],
    name: 'getStakeInfo',
    outputs: [
      {
        components: [
          { name: 'amount', type: 'uint256' },
          { name: 'rewardDebt', type: 'uint256' },
          { name: 'unstakeAmount', type: 'uint256' },
          { name: 'unstakeTime', type: 'uint256' },
          { name: 'lastStakeTime', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTotalStaked',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'layer2Manager',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'staker', type: 'address' },
      { name: 'sequencer', type: 'address' },
    ],
    name: 'pendingRewards',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'seigManager',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ton',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unbondingPeriod',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'wton',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },

  // Write Functions
  {
    inputs: [],
    name: 'claimCommission',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'claimRewards',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deregisterSequencer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'emergencyWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'fromSequencer', type: 'address' },
      { name: 'toSequencer', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'redelegate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'layer2', type: 'address' },
      { name: 'operatorManager', type: 'address' },
      { name: 'commission', type: 'uint256' },
    ],
    name: 'registerSequencer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'enabled', type: 'bool' }],
    name: 'setAutoTrigger',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'sequencer', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'stake',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'triggerSeigniorage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'sequencer', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'unstake',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'newCommission', type: 'uint256' }],
    name: 'updateCommission',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'sequencer', type: 'address' }],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export const ERC20_ABI = [
  {
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
