#!/bin/bash
# Connect to Local Infrastructure (Bash)
# Reads deployment.json from local-infra and updates contract addresses
# Usage: ./scripts/connect-local.sh

set -e

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        DELEGATE-STAKING: Connect to Local Infra              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Paths
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_INFRA_PATH="$(dirname "$PROJECT_ROOT")/local-infra"
DEPLOYMENT_FILE="$LOCAL_INFRA_PATH/deployment.json"
ADDRESSES_FILE="$PROJECT_ROOT/src/lib/contracts/addresses.ts"

cd "$PROJECT_ROOT"

# Step 1: Check if local-infra exists
echo "[1/4] Checking local-infra..."

if [ ! -d "$LOCAL_INFRA_PATH" ]; then
    echo "Error: local-infra not found at $LOCAL_INFRA_PATH"
    echo ""
    echo "Please clone or create local-infra first:"
    echo "  cd ../local-infra"
    echo "  ./scripts/setup.sh"
    exit 1
fi
echo "  local-infra found"

# Step 2: Check if deployment.json exists
echo "[2/4] Reading deployment.json..."

if [ ! -f "$DEPLOYMENT_FILE" ]; then
    echo "Error: deployment.json not found"
    echo ""
    echo "Please run local-infra setup first:"
    echo "  cd $LOCAL_INFRA_PATH"
    echo "  ./scripts/setup.sh"
    exit 1
fi

# Read deployment using jq or basic parsing
if command -v jq &> /dev/null; then
    RPC_URL=$(jq -r '.rpcUrl' "$DEPLOYMENT_FILE")
    DELEGATE_STAKING=$(jq -r '.contracts.delegateStaking' "$DEPLOYMENT_FILE")
    TON=$(jq -r '.contracts.ton' "$DEPLOYMENT_FILE")
    WTON=$(jq -r '.contracts.wton' "$DEPLOYMENT_FILE")
else
    # Basic grep parsing fallback
    RPC_URL=$(grep -o '"rpcUrl": *"[^"]*"' "$DEPLOYMENT_FILE" | cut -d'"' -f4)
    DELEGATE_STAKING=$(grep -o '"delegateStaking": *"[^"]*"' "$DEPLOYMENT_FILE" | cut -d'"' -f4)
    TON=$(grep -o '"ton": *"[^"]*"' "$DEPLOYMENT_FILE" | cut -d'"' -f4)
    WTON=$(grep -o '"wton": *"[^"]*"' "$DEPLOYMENT_FILE" | cut -d'"' -f4)
fi

# Verify Anvil is running
RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
    "$RPC_URL" 2>/dev/null || echo '{}')

if echo "$RESPONSE" | grep -q "0x7a69"; then
    echo "  Anvil running at $RPC_URL"
else
    echo "Error: Anvil is not running at $RPC_URL"
    echo ""
    echo "Please start local-infra first:"
    echo "  cd $LOCAL_INFRA_PATH"
    echo "  ./scripts/setup.sh"
    exit 1
fi

# Step 3: Update addresses.ts with local addresses
echo "[3/4] Updating contract addresses..."

# Create the new LOCAL_ADDRESSES block
NEW_BLOCK="// Local development addresses (anvil)
// Auto-updated by connect-local.sh from local-infra/deployment.json
export const LOCAL_ADDRESSES: ChainAddresses = {
  delegateStaking: '$DELEGATE_STAKING', // DelegateStakingV3
  ton: '$TON',
  wton: '$WTON',
};"

# Use perl for cross-platform multiline replacement
if command -v perl &> /dev/null; then
    perl -i -0pe "s|// Local development addresses.*?export const LOCAL_ADDRESSES: ChainAddresses = \{[^}]+\};|$NEW_BLOCK|s" "$ADDRESSES_FILE"
else
    # Fallback: Create a temp file approach
    echo "Warning: perl not found, using manual replacement"
    # Read file, replace block, write back
    python3 -c "
import re
with open('$ADDRESSES_FILE', 'r') as f:
    content = f.read()
new_block = '''$NEW_BLOCK'''
content = re.sub(
    r'// Local development addresses.*?export const LOCAL_ADDRESSES: ChainAddresses = \{[^}]+\};',
    new_block,
    content,
    flags=re.DOTALL
)
with open('$ADDRESSES_FILE', 'w') as f:
    f.write(content)
" 2>/dev/null || echo "Warning: Could not auto-update addresses.ts, please update manually"
fi

echo "  addresses.ts updated"

# Step 4: Create .env.local for any env vars needed
echo "[4/4] Creating .env.local..."

cat > .env.local << EOF
# Delegate-staking Local Environment
# Generated by connect-local.sh at $(date)
# Connected to: $LOCAL_INFRA_PATH

# Local Anvil RPC
NEXT_PUBLIC_LOCAL_RPC_URL=$RPC_URL
NEXT_PUBLIC_IS_LOCAL=true

# Optional: WalletConnect Project ID
# NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=
EOF

echo "  .env.local created"
echo ""

# Summary
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    CONNECTED!                                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Contract Addresses:"
echo "  DelegateStaking: $DELEGATE_STAKING"
echo "  TON:             $TON"
echo "  WTON:            $WTON"
echo ""
echo "RPC URL: $RPC_URL"
echo ""
echo "Run 'npm run dev' to start the frontend"
