# Connect to Local Infrastructure (Windows PowerShell)
# Reads deployment.json from local-infra and updates contract addresses
# Usage: .\scripts\connect-local.ps1

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║        DELEGATE-STAKING: Connect to Local Infra              ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Paths
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$LocalInfraPath = Join-Path (Split-Path -Parent $ProjectRoot) "local-infra"
$DeploymentFile = Join-Path $LocalInfraPath "deployment.json"
$AddressesFile = Join-Path $ProjectRoot "src\lib\contracts\addresses.ts"

Set-Location $ProjectRoot

# Step 1: Check if local-infra exists
Write-Host "[1/4] Checking local-infra..." -ForegroundColor Yellow

if (-not (Test-Path $LocalInfraPath)) {
    Write-Host "Error: local-infra not found at $LocalInfraPath" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please clone or create local-infra first:" -ForegroundColor Yellow
    Write-Host "  cd ..\local-infra"
    Write-Host "  .\scripts\setup.ps1"
    exit 1
}
Write-Host "  local-infra found" -ForegroundColor Green

# Step 2: Check if deployment.json exists
Write-Host "[2/4] Reading deployment.json..." -ForegroundColor Yellow

if (-not (Test-Path $DeploymentFile)) {
    Write-Host "Error: deployment.json not found" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please run local-infra setup first:" -ForegroundColor Yellow
    Write-Host "  cd $LocalInfraPath"
    Write-Host "  .\scripts\setup.ps1"
    exit 1
}

# Read deployment
$deployment = Get-Content $DeploymentFile -Raw | ConvertFrom-Json
$RpcUrl = $deployment.rpcUrl

# Verify Anvil is running
try {
    $response = Invoke-RestMethod -Uri $RpcUrl -Method Post -ContentType "application/json" -Body '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' -TimeoutSec 5
    if ($response.result -ne "0x7a69") {
        throw "Wrong chain"
    }
    Write-Host "  Anvil running at $RpcUrl" -ForegroundColor Green
} catch {
    Write-Host "Error: Anvil is not running at $RpcUrl" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please start local-infra first:" -ForegroundColor Yellow
    Write-Host "  cd $LocalInfraPath"
    Write-Host "  .\scripts\setup.ps1"
    exit 1
}

# Step 3: Update addresses.ts with local addresses
Write-Host "[3/4] Updating contract addresses..." -ForegroundColor Yellow

$delegateStaking = $deployment.contracts.delegateStaking
$ton = $deployment.contracts.ton
$wton = $deployment.contracts.wton

# Read current addresses.ts
$addressesContent = Get-Content $AddressesFile -Raw

# Update LOCAL_ADDRESSES using regex
$newLocalAddresses = @"
// Local development addresses (anvil)
// Auto-updated by connect-local.ps1 from local-infra/deployment.json
export const LOCAL_ADDRESSES: ChainAddresses = {
  delegateStaking: '$delegateStaking', // DelegateStakingV3
  ton: '$ton',
  wton: '$wton',
};
"@

# Replace the LOCAL_ADDRESSES block
$pattern = '// Local development addresses.*?export const LOCAL_ADDRESSES: ChainAddresses = \{[^}]+\};'
$addressesContent = [regex]::Replace($addressesContent, $pattern, $newLocalAddresses, [System.Text.RegularExpressions.RegexOptions]::Singleline)

# Write updated file
$addressesContent | Set-Content $AddressesFile -NoNewline
Write-Host "  addresses.ts updated" -ForegroundColor Green

# Step 4: Create .env.local for any env vars needed
Write-Host "[4/4] Creating .env.local..." -ForegroundColor Yellow

$envContent = @"
# Delegate-staking Local Environment
# Generated by connect-local.ps1 at $(Get-Date)
# Connected to: $LocalInfraPath

# Local Anvil RPC
NEXT_PUBLIC_LOCAL_RPC_URL=$RpcUrl
NEXT_PUBLIC_IS_LOCAL=true

# Optional: WalletConnect Project ID
# NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=
"@

$envContent | Out-File -FilePath ".env.local" -Encoding utf8
Write-Host "  .env.local created" -ForegroundColor Green
Write-Host ""

# Summary
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                    CONNECTED!                                ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "Contract Addresses:" -ForegroundColor White
Write-Host "  DelegateStaking: $delegateStaking" -ForegroundColor White
Write-Host "  TON:             $ton" -ForegroundColor White
Write-Host "  WTON:            $wton" -ForegroundColor White
Write-Host ""
Write-Host "RPC URL: $RpcUrl" -ForegroundColor White
Write-Host ""
Write-Host "Run 'npm run dev' to start the frontend" -ForegroundColor Yellow
