#!/bin/bash
#
# Generate Solidity code to setup allocs using vm.etch()
#

set -e

ALLOCS_FILE="${1:-.devnet/allocs-l1.json}"
OUTPUT_FILE="${2:-script/SetupL1Allocs.sol}"

if [ ! -f "$ALLOCS_FILE" ]; then
    echo "Error: Allocs file not found: $ALLOCS_FILE"
    exit 1
fi

echo "Generating Solidity allocs setup code..."
echo "  Input: $ALLOCS_FILE"
echo "  Output: $OUTPUT_FILE"

# Count total accounts
TOTAL_ACCOUNTS=$(jq 'keys | length' "$ALLOCS_FILE")
echo "  Total accounts: $TOTAL_ACCOUNTS"

# Generate Solidity file
cat > "$OUTPUT_FILE" << 'SOLIDITY_HEADER'
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "forge-std/Script.sol";
import "forge-std/console.sol";

/**
 * @title SetupL1Allocs
 * @notice Sets up L1 genesis state from allocs-l1.json using vm.etch() and vm.store()
 * @dev This is generated by scripts/generate-allocs-setup.sh
 */
contract SetupL1Allocs is Script {
    function setupAllocs() internal {
        console.log("Setting up L1 allocs...");

SOLIDITY_HEADER

# Process each account
COUNTER=0
jq -r 'to_entries[] | @json' "$ALLOCS_FILE" | while read -r account; do
    ADDR=$(echo "$account" | jq -r '.key')
    CODE=$(echo "$account" | jq -r '.value.code // "0x"')
    BALANCE=$(echo "$account" | jq -r '.value.balance // "0x0"')
    NONCE=$(echo "$account" | jq -r '.value.nonce // "0x0"')

    # Only process accounts with code (contracts)
    if [ "$CODE" != "0x" ] && [ "$CODE" != "null" ]; then
        COUNTER=$((COUNTER + 1))

        # Convert address to hex bytes format (no 0x prefix)
        ADDR_BYTES="${ADDR:2}"

        # Write vm.etch for bytecode (use bytes20 to bypass checksum validation)
        cat >> "$OUTPUT_FILE" << SOLIDITY_ETCH
        // Account $COUNTER: $ADDR
        vm.etch(address(bytes20(hex"$ADDR_BYTES")), hex"${CODE:2}");
SOLIDITY_ETCH

        # Set balance if non-zero
        if [ "$BALANCE" != "0x0" ] && [ "$BALANCE" != "0x" ] && [ "$BALANCE" != "null" ]; then
            cat >> "$OUTPUT_FILE" << SOLIDITY_BALANCE
        vm.deal(address(bytes20(hex"$ADDR_BYTES")), $BALANCE);
SOLIDITY_BALANCE
        fi

        # Set nonce if non-zero
        if [ "$NONCE" != "0x0" ] && [ "$NONCE" != "0x" ] && [ "$NONCE" != "null" ]; then
            cat >> "$OUTPUT_FILE" << SOLIDITY_NONCE
        vm.setNonce(address(bytes20(hex"$ADDR_BYTES")), uint64($NONCE));
SOLIDITY_NONCE
        fi

        # Process storage
        STORAGE=$(echo "$account" | jq -r '.value.storage // {}')
        if [ "$STORAGE" != "{}" ] && [ "$STORAGE" != "null" ]; then
            echo "$STORAGE" | jq -r 'to_entries[] | "\(.key) \(.value)"' | while read -r slot value; do
                cat >> "$OUTPUT_FILE" << SOLIDITY_STORAGE
        vm.store(address(bytes20(hex"$ADDR_BYTES")), bytes32($slot), bytes32($value));
SOLIDITY_STORAGE
            done
        fi

        echo "" >> "$OUTPUT_FILE"

        # Progress indicator every 10 accounts
        if [ $((COUNTER % 10)) -eq 0 ]; then
            echo "  Processed $COUNTER contracts..."
        fi
    fi
done

# Add footer
cat >> "$OUTPUT_FILE" << 'SOLIDITY_FOOTER'
        console.log("L1 allocs setup complete");
        console.log("  Total contracts deployed via vm.etch():", getContractCount());
    }

    function getContractCount() internal pure returns (uint256) {
        // This will be updated by the generation script
        return ACCOUNT_COUNT_PLACEHOLDER;
    }

    function run() public {
        console.log("=== SetupL1Allocs Standalone Run ===");
        setupAllocs();
        console.log("L1 allocs setup complete");
        console.log("  Total contracts deployed via vm.etch():", getContractCount());
    }
}
SOLIDITY_FOOTER

# Update contract count
ACTUAL_COUNT=$(grep -c "vm.etch" "$OUTPUT_FILE" || echo "0")
if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/ACCOUNT_COUNT_PLACEHOLDER/$ACTUAL_COUNT/g" "$OUTPUT_FILE"
else
    sed -i "s/ACCOUNT_COUNT_PLACEHOLDER/$ACTUAL_COUNT/g" "$OUTPUT_FILE"
fi

echo "✓ Generated Solidity allocs setup"
echo "  Contracts with bytecode: $ACTUAL_COUNT"
