#!/bin/bash
# =============================================================================
# Sync Web UI Config from Devnet Addresses
# =============================================================================
# Reads addresses from .devnet/addresses.json and scripts/config/optimism-addresses.json
# and updates web-ui/src/config.ts accordingly.
#
# Usage:
#   ./scripts/sync-web-ui-config.sh
# =============================================================================

set -eo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DEVNET_ADDRESSES="$PROJECT_ROOT/.devnet/addresses.json"
OPTIMISM_ADDRESSES="$PROJECT_ROOT/scripts/config/optimism-addresses.json"
CONFIG_TS="$PROJECT_ROOT/web-ui/src/config.ts"

echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Sync Web UI Config from Devnet Addresses                 ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check required files
if [ ! -f "$DEVNET_ADDRESSES" ]; then
    echo -e "${RED}Error: .devnet/addresses.json not found${NC}"
    echo "Run ./scripts/generate-optimism-allocs-sepolia.sh first"
    exit 1
fi

if [ ! -f "$OPTIMISM_ADDRESSES" ]; then
    echo -e "${RED}Error: scripts/config/optimism-addresses.json not found${NC}"
    echo "Run ./scripts/generate-optimism-allocs-sepolia.sh first"
    exit 1
fi

if [ ! -f "$CONFIG_TS" ]; then
    echo -e "${RED}Error: web-ui/src/config.ts not found${NC}"
    exit 1
fi

# Read addresses from .devnet/addresses.json (TON Staking V3)
TON=$(jq -r '.ton' "$DEVNET_ADDRESSES")
WTON=$(jq -r '.wton' "$DEVNET_ADDRESSES")
SEIG_MANAGER=$(jq -r '.seigManagerProxy' "$DEVNET_ADDRESSES")
DEPOSIT_MANAGER=$(jq -r '.depositManagerProxy' "$DEVNET_ADDRESSES")
LAYER2_MANAGER=$(jq -r '.layer2ManagerProxy' "$DEVNET_ADDRESSES")
L1_BRIDGE_REGISTRY=$(jq -r '.l1BridgeRegistryProxy' "$DEVNET_ADDRESSES")
LAYER2_REGISTRY=$(jq -r '.layer2RegistryProxy' "$DEVNET_ADDRESSES")
RAT=$(jq -r '.ratProxy' "$DEVNET_ADDRESSES")
VALIDATOR_REWARD=$(jq -r '.validatorRewardProxy' "$DEVNET_ADDRESSES")

# Read addresses from scripts/config/optimism-addresses.json (Optimism Stack)
SYSTEM_CONFIG=$(jq -r '.SystemConfigProxy' "$OPTIMISM_ADDRESSES")
DISPUTE_GAME_FACTORY=$(jq -r '.DisputeGameFactoryProxy' "$OPTIMISM_ADDRESSES")

echo -e "${YELLOW}Addresses to sync:${NC}"
echo "  TON:                 $TON"
echo "  WTON:                $WTON"
echo "  SeigManager:         $SEIG_MANAGER"
echo "  DepositManager:      $DEPOSIT_MANAGER"
echo "  Layer2Manager:       $LAYER2_MANAGER"
echo "  L1BridgeRegistry:    $L1_BRIDGE_REGISTRY"
echo "  Layer2Registry:      $LAYER2_REGISTRY"
echo "  RAT:                 $RAT"
echo "  ValidatorReward:     $VALIDATOR_REWARD"
echo "  SystemConfig:        $SYSTEM_CONFIG"
echo "  DisputeGameFactory:  $DISPUTE_GAME_FACTORY"
echo ""

# Generate new config.ts
cat > "$CONFIG_TS" <<EOF
// TON Staking V3 Configuration
// Auto-generated by scripts/sync-web-ui-config.sh
export const CONFIG = {
  chainId: 900,  // Local devnet
  rpcUrl: 'http://localhost:8546',
  l2RpcUrl: 'http://localhost:9545',
  chainName: 'TON Staking V3 Sepolia Fork',
  nativeCurrency: {
    name: 'Ethereum',
    symbol: 'ETH',
    decimals: 18,
  },

  // Contract addresses (synced from .devnet/addresses.json)
  contracts: {
    // Tokens
    ton: '${TON}',
    wton: '${WTON}',

    // Core Managers
    seigManager: '${SEIG_MANAGER}',
    depositManager: '${DEPOSIT_MANAGER}',
    layer2Manager: '${LAYER2_MANAGER}',
    l1BridgeRegistry: '${L1_BRIDGE_REGISTRY}',
    layer2Registry: '${LAYER2_REGISTRY}',

    // V3 Components
    rat: '${RAT}',
    validatorReward: '${VALIDATOR_REWARD}',

    // Optimism Stack
    systemConfig: '${SYSTEM_CONFIG}',
    disputeGameFactory: '${DISPUTE_GAME_FACTORY}',
  },
};

// Test accounts (from Anvil)
export const TEST_ACCOUNTS = [
  {
    name: 'Deployer / Operator',
    address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    privateKey: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
    role: 'L2 Operator & Sequencer',
  },
  {
    name: 'TON Staking Deployer',
    address: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
    privateKey: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
    role: 'Admin (Manager Role)',
  },
  {
    name: 'Validator #1',
    address: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
    privateKey: '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6',
    role: 'RAT Validator',
  },
  {
    name: 'Validator #2',
    address: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
    privateKey: '0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a',
    role: 'RAT Validator',
  },
  {
    name: 'Validator #3',
    address: '0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc',
    privateKey: '0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba',
    role: 'RAT Validator',
  },
  {
    name: 'Personal Test',
    address: '0x976EA74026E726554dB657fA54763abd0C3a0aa9',
    privateKey: '0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e',
    role: 'Personal Account (Anvil #6)',
  },
];

// Rollup types
export const ROLLUP_TYPES = {
  0: 'Invalid',
  1: 'Optimism Legacy',
  2: 'Optimism Bedrock Native',
  3: 'Optimism Bedrock DisputeGame',
};

// Status codes
export const LAYER2_STATUS = {
  0: 'None',
  1: 'Registered',
  2: 'Paused',
};
EOF

echo -e "${GREEN}  ✓ web-ui/src/config.ts updated${NC}"

# Update web-ui/public/addresses.json (runtime fetch by App.tsx)
PUBLIC_DIR="$PROJECT_ROOT/web-ui/public"
cp "$DEVNET_ADDRESSES" "$PUBLIC_DIR/addresses.json"
echo -e "${GREEN}  ✓ web-ui/public/addresses.json updated${NC}"

# Update web-ui/public/optimism-addresses.json (runtime fetch by App.tsx)
cp "$OPTIMISM_ADDRESSES" "$PUBLIC_DIR/optimism-addresses.json"
echo -e "${GREEN}  ✓ web-ui/public/optimism-addresses.json updated${NC}"

echo ""
echo -e "${GREEN}✓ All web-ui config synced successfully${NC}"
echo -e "${CYAN}Next: cd web-ui && npm run dev${NC}"
